version: "3.7"

services:
  frontend:
    image: '${CI_REGISTRY_IMAGE}/frontend:latest'
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - ENV=production
      - API_URL=${API_URL}
      - API_KEY_TOKEN=${API_KEY_TOKEN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    deploy:
      placement:
        constraints:
          - node.role == worker
          labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.constraint-label=traefik-public
            - traefik.http.routers.front-http.rule=Host(`kod3rsstore.com`)
            - traefik.http.routers.front-http.entrypoints=http
            - traefik.http.routers.front-http.middlewares=https-redirect
            - traefik.http.routers.front-https.rule=Host(`kod3rsstore.com`)
            - traefik.http.routers.front-https.entrypoints=https
            - traefik.http.routers.front-https.tls=true
            - traefik.http.routers.front-https.tls.certresolver=le
            - traefik.http.services.front.loadbalancer.server.port=4000
    networks:
      - default
      - traefik-public
networks:
  traefik-public:
    external: true
