version: "3.7"

services:
  frontend:
    image: 'frontend:latest'
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - ENV=production
      - PORT=4000
      - API_URL=${API_URL}
      - API_KEY_TOKEN=${API_KEY_TOKEN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
